
const dummyEpisodes = {
    then(callback) {
        callback({
            "uuid": "5677f369-bb80-4862-af22-b75cd06bca71",
            "datePublished": 1452330487,
            "name": "Casefile True Crime",
            "description": "Fact is scarier than fiction. Subscribe to Casefile Premium to receive ad-free episodes released one week early, along with access to bonus Q&A’s, our exclusive show ‘Behind the Files’, and more.",
            "imageUrl": "https://audioboom.com/i/36767849.jpg",
            "itunesId": 998568017,
            "hash": "f4adad9a8bdaac83c6835138d7ba17f1ef6576a29faba0d30540135cea07d29d",
            "childrenHash": "16c0ae7df881713ab33db64978ede301168bb57bac89b68aa1b297372e55c2a0",
            "episodes": [
                {
                    "uuid": "522dcec1-dfc1-4a1a-9e68-e421aa59188d",
                    "name": "299: Case 255: Rudolf Rupp",
                    "description": "<div>When 52-year-old German farmer Rudolf Rupp failed to return home from a night out drinking in the town of Neuburg an der Donau, several questions were raised. Had Rudolf accidentally driven into the nearby Donau River? Had he taken his own life? Or was he the victim of something more sinister?  <br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://www.instagram.com/caseys.snaps/\">Anonymous Host</a><br>\nResearch &amp; writing – Elsha McGill<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>For all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-255-rudolf-rupp\">casefilepodcast.com/case-255-rudolf-rupp</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8334902.mp3?modified=1689334811&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40742258.jpg"
                },
                {
                    "uuid": "f4fdf2c6-3ae6-4a33-9500-0c8a1604004a",
                    "name": "Case 254: Winsie Hau",
                    "description": "<div>*** <em>Content warning: child victim</em> ***<br>\nOn the afternoon of January 14, 2012, 15-year-old Winsie Hau was attacked with a knife by a 14-year-old boy. Winsie's father was also attacked, and while he survived his injuries, Winsie did not.  <br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://www.instagram.com/caseys.snaps/\">Anonymous Host</a><br>\nResearch &amp; writing – Holly Hoyd<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>For all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-254-winsie-hau/\">casefilepodcast.com/case-254-winsie-hau</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8331934.mp3?modified=1688798072&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40725323.jpg"
                },
                {
                    "uuid": "01195513-3d33-4f36-9803-fa53faf48294",
                    "name": "Case 253: Aarushi Talwar & Hemraj Banjade",
                    "description": "<div>*** <em>Content warning: child victim, sexual assault</em> ***<br>\nWhen Rajesh and Nupur Talwar went to wake their 13-year-old daughter Aarushi on the morning of Friday, May 16 2008, the couple were shocked to find her brutally murdered in her bed.<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://www.instagram.com/caseys.snaps/\">Anonymous Host</a><br>\nResearch &amp; writing – Erin Munro<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>For all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-253-aarushi-talwar-hemraj-banjade/\">casefilepodcast.com/case-253-aarushi-talwar-hemraj-banjade</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8326638.mp3?modified=1688203490&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40697126.jpg"
                },
                {
                    "uuid": "1791c62b-b9e5-418f-a1a9-db9b824c6729",
                    "name": "Case 252: Margaret Maher, Mersina Halvagis & Nicole Patterson",
                    "description": "<div>\n<em>*** Content warning: serial rapist and killer, sexual assault, stalking ***<br>\n</em>When Melbourne women Margaret Maher, Mersina Halvagis and Nicole Patterson were found brutally murdered in the late 1990s, police didn’t immediately link the crimes. The killer left behind no incriminating evidence, indicating he was an experienced offender who knew how to beat the system. Little did investigators know, the story began almost 30 years earlier, when a 15-year-old boy knocked on his neighbour’s door and asked to borrow a knife.<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://www.instagram.com/caseys.snaps/\">Anonymous Host</a><br>\nResearch &amp; writing – Milly Raso<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>For all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-252-margaret-maher-mersina-halvagis-nicole-patterson/\">casefilepodcast.com/case-252-margaret-maher-mersina-halvagis-nicole-patterson</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8323023.mp3?modified=1687598189&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40676752.jpg"
                },
                {
                    "uuid": "e2a3d5f5-e976-4129-b989-738476a88864",
                    "name": "295: Case 251: The Caldwell Farmhouse Murders",
                    "description": "<div>\n<em>*** Content warning: Child victim, animal cruelty ***<br>\n</em>When single mother Nadja Medley met an older man named Mike Bullinger, she finally found happiness after a difficult few years. As well as being a fun, kind-hearted partner, Mike was a wonderful father figure to Nadja’s 14-year-old daughter Payton. In May 2017, the three of them moved from Ogden, Utah, to a farmhouse Mike had just bought in Caldwell, Idaho.<br>\n<br>\nBut when a woman by the name of Cheryl Baker arrived unannounced at the property one day, tragedy ensued. <br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://www.instagram.com/caseys.snaps/\">Anonymous Host</a><br>\nResearch &amp; writing – Erin Munro<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>For all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-251-the-caldwell-farmhouse-murders/\">casefilepodcast.com/case-251-the-caldwell-farmhouse-murders</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8319523.mp3?modified=1689337102&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40655426.jpg"
                },
                {
                    "uuid": "b14da74e-25f7-4f43-8372-73a911f0587f",
                    "name": "Case 250: Amy Boyer",
                    "description": "<div>\n<em>*** Content warning: Mental illness, stalking, gun violence ***<br>\n</em>Amy Boyer was a popular teen in her hometown of Nashua, New Hampshire. Her life was busy between school, work and social commitments. Full of joy and love, Amy naturally drew in those around her – including a troubled young man named Liam Youens.<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://www.instagram.com/caseys.snaps/\">Anonymous Host</a><br>\nResearch &amp; writing – Milly Raso<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>For all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-250-amy-boyer/\">casefilepodcast.com/case-250-amy-boyer</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8314138.mp3?modified=1686211463&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40624450.jpg"
                },
                {
                    "uuid": "c5c674bb-be39-46a3-b4d4-9ce35dd7163d",
                    "name": "Case 249: Lorraine Wilson & Wendy Evans",
                    "description": "<div>\n<em>*** Content warning: Sexual assault ***<br>\n</em>When trainee nurses Lorraine Wilson and Wendy Evans failed to return to work in Sydney after a holiday around Australia in 1974, fears arose that they could have fallen victim to the so-called Gold Coast Hitchhiker Murderer. But when a discovery is made in the rural town of Murphy’s Creek years later, an even more disturbing possibility emerges...<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://www.instagram.com/caseys.snaps/\">Anonymous Host</a><br>\nResearch &amp; writing – Elsha McGill<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>\n<br>\nFor all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-249-lorraine-wilson-wendy-evans/\">casefilepodcast.com/case-249-lorraine-wilson-wendy-evans</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8311485.mp3?modified=1685785562&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40609435.jpg"
                },
                {
                    "uuid": "8d4ff51b-40f6-4d43-afc8-844c0bc61399",
                    "name": "Case 248: Abraham Shakespeare",
                    "description": "<div>\n<em>*** Content warning: Gun violence ***<br>\n</em>When 41-year-old Abraham Shakespeare won the 30 million dollar Florida Lottery prize, his underprivileged life changed overnight. Yet, he quickly realised his newfound wealth was a curse. Despite showing limitless charity, he became demoralised by the pressure and expectations thrust upon him by those seeking his money...<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Milly Raso<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>This episode's sponsors:<br>\n<a href=\"https://www.ziprecruiter.com/casefile\">ZipRecruiter</a> – Post your jobs for FREE<br>\n<br>\nFor all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-248-abraham-shakespeare/\">casefilepodcast.com/case-248-abraham-shakespeare</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8307263.mp3?modified=1686663720&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40590548.jpg"
                },
                {
                    "uuid": "168dd00f-96a0-434a-a4f2-49ad5ff22f1b",
                    "name": "Case 247: Nina Puganova, Irina Trasyn & Anastasia Mikhailova",
                    "description": "<div>In the summer of 1980, Theodosius Glukharev received a series of harrowing deliveries to his home in Kishinev, Soviet Moldova. The contents ultimately unravelled the murders of three women – Nina Puganova, Irina Trasyn &amp; Anastasia Mikhailova...<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Holly Boyd<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>This episode's sponsors:<br>\n<a href=\"https://casefilepresents.com/in-the-shadows/\">In the Shadows</a> – Listen to a podcast from Casefile Presents (available everywhere)<br>\n<br>\nFor all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-247-nina-puganova-irina-trasyn-anastasia-mikhailova/\">casefilepodcast.com/case-247-nina-puganova-irina-trasyn-anastasia-mikhailova</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8304141.mp3?modified=1686663582&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40568925.jpg"
                },
                {
                    "uuid": "c67e9884-8745-49de-934c-bfb6689c2e01",
                    "name": "Case 246: Grégory Villemin (Part 2)",
                    "description": "<div>[Part 2 of 2]<br>\n*** Content Warning: child victim ***<br>\n<br>\nAfter grieving father Jean-Marie Villemin takes revenge for his son’s death into his own hands, the investigation into Grégory Villemin’s death takes a series of unexpected turns.<em> </em><br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Elsha McGill<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a> and<a href=\"http://www.andrewjoslynmusic.com/\"> Andrew Joslyn</a><br>\n<br>\nSubscribe for ad-free episodes and bonus content:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Join Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Join Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Join Patreon</a></li>\n</ul>\n<div>For all credits and sources please visit <a href=\"https://casefilepodcast.com/case-246-gregory-villemin-part-2/\">casefilepodcast.com/case-246-gregory-villemin-part-2</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8300365.mp3?modified=1685789146&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40548099.jpg"
                },
                {
                    "uuid": "6e7e4e3b-f612-4f8d-8fc8-aadab0873a28",
                    "name": "Case 246: Grégory Villemin (Part 1)",
                    "description": "<div>[Part 1 of 2]<br>\n*** Content Warning: child victim ***<br>\n<br>\nThe extended Villemin family lived in the Vosges region of north-eastern France. From 1981, several members of the family started to receive anonymous, threatening phone calls from a mysterious caller they eventually labelled The Crow. <br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Elsha McGill<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a> and<a href=\"http://www.andrewjoslynmusic.com/\"> Andrew Joslyn</a><br>\n<br>\nThis episode's sponsors:<br>\n<a href=\"https://www.betterhelp.com/casefile\">BetterHelp</a> – Get 10% off your first month of professional counselling with a licensed therapist<br>\n<br>\nSubscribe for ad-free episodes and bonus content:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Join Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Join Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Join Patreon</a></li>\n</ul>\n<div>For all credits and sources please visit <a href=\"https://casefilepodcast.com/case-246-gregory-villemin-part-1/\">casefilepodcast.com/case-246-gregory-villemin-part-1</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8296409.mp3?modified=1683360492&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40525730.jpg"
                },
                {
                    "uuid": "bc75fbab-e551-4c32-905f-82ecad0725fa",
                    "name": "Case 245: Sherri Papini",
                    "description": "<div>When married mother of two, Sherri Papini, goes missing near her home in Redding, California, the community is gripped by fear. Suspicion immediately falls on Sherri’s husband, Keith Papini, but an even darker theory emerges – what if Sherri was the victim of a human trafficking ring?<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Elsha McGill<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>For all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-245-sherri-papini/\">casefilepodcast.com/case-245-sherri-papini</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8290429.mp3?modified=1685952008&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40493588.jpg"
                },
                {
                    "uuid": "71b708bb-9963-477e-948d-2d73684157f3",
                    "name": "Case 244: Engla Höglund & Pernilla Hellgren",
                    "description": "<div>*** Warning: This case involves a child victim ***<em><br>\n</em>On April 5 2008, 10-year-old Engla Höglund went missing while cycling home from soccer practice near the small Swedish town of Stjärnsund. As news spread, a witness came forward who had captured Engla in a photograph just moments before she disappeared.<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Holly Boyd <br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>This episode's sponsors:<br>\n<a href=\"https://www.zocdoc.com/casefile\">Zocdoc</a> –  Find a doctor near you <br>\n<br>\nFor all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-244-engla-hoglund-pernilla-hellgren/\">casefilepodcast.com/case-244-engla-hoglund-pernilla-hellgren</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8285901.mp3?modified=1684670376&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40470210.jpg"
                },
                {
                    "uuid": "f3e3d508-5169-4597-a0d4-39f6a42a1d29",
                    "name": "Case 243: Deidre Kennedy",
                    "description": "<div>*** Warning: This case involves a child victim ***<em><br>\n</em>On April 14 1973, the Kennedy family awoke in their Ipswich, Queensland unit to discover the unthinkable. 16-month-old Deidre Kennedy was missing from her cot, having been abducted by an intruder overnight.<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Elsha McGill  <br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>This episode's sponsors:<br>\n<a href=\"https://apps.apple.com/gb/app/doordash-food-delivery/id719972451\">DoorDash</a> – Get free delivery plus 50% off your first order of up to $20 value with promo code ‘FILE’<br>\n<a href=\"https://simplisafe.com/casefile\">SimpliSafe</a> – Get a free indoor security camera and 25% off your order <br>\n<br>\nFor all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-243-deidre-kennedy/\">casefilepodcast.com/case-243-deidre-kennedy</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8281926.mp3?modified=1684064688&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40449163.jpg"
                },
                {
                    "uuid": "7eeff5d4-7a64-48a1-b806-44e222ca9847",
                    "name": "Case 242: The Investor Murders",
                    "description": "<div>*** Warning: This case involves a child victim ***<strong><em><br>\n</em></strong>On the afternoon of Tuesday, September 7 1982, residents of the tiny Alaskan fishing village of Craig noticed smoke across the harbour. A fishing vessel was on fire. It belonged to successful Washington fisherman Mark Coulthurst, who was travelling with his wife Irene, their two children, Kimberley and John, and four teenage deckhands: Dean Moon, Michael Stewart, Jerome Keown and Chris Heyman. <br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Erin Munro<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>This episode's sponsors:<br>\n<a href=\"https://www.article.com/casefile\">Article</a> – Get $50 off your first order of $100 or more<br>\n<a href=\"https://www.betterhelp.com/casefile\">BetterHelp</a> – Get 10% off your first month of professional counselling with a licensed therapist<br>\n<br>\nFor all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-242-the-investor-murders/\">casefilepodcast.com/case-242-the-investor-murders</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8277365.mp3?modified=1683360234&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40425481.jpg"
                },
                {
                    "uuid": "6be0f7d4-e10a-4217-ac5f-385bd88f9424",
                    "name": "Case 241: Harry & Nicola Fuller",
                    "description": "<div>On February 10 1993, East Sussex police were summoned to conduct a welfare check at the Wadhurst cottage of newlyweds, Harry and Nicola Fuller. What they found inside left the tight-knit community in shock. <br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Elsha McGill<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>This episode's sponsors:<br>\n<a href=\"https://apps.apple.com/gb/app/doordash-food-delivery/id719972451\">DoorDash</a> – Get free delivery plus 50% off your first order of up to $20 value with promo code ‘FILE’<br>\n<a href=\"https://www.ziprecruiter.com/casefile\">ZipRecruiter</a> – Post your jobs for FREE<br>\n<a href=\"https://www.betterhelp.com/casefile\">BetterHelp</a> – Get 10% off your first month of professional counselling with a licensed therapist<br>\n<br>\nFor all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-241-harry-nicola-fuller/\">casefilepodcast.com/case-241-harry-nicola-fuller</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8273397.mp3?modified=1682751463&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40403573.jpg"
                },
                {
                    "uuid": "23faf8cd-871a-4c09-9cbd-b0de28afd124",
                    "name": "Case 240: JasonInHell",
                    "description": "<div>*** Warning: This case involves a child victim ***<br>\n<br>\nBy late 2016, Jason and Brandi Worley’s marriage was crumbling. Regardless of what happened between them, they promised to always put their two children, Tyler and Charlee, first. <br>\n<br>\nMeanwhile, a user going by the name of JasonInHell logged onto Reddit and clicked on a forum titled: relationship_advice.<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Milly Raso<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>This episode's sponsors:<br>\n<a href=\"https://www.hellofresh.com/casefile60\">Hello Fresh</a> – Use code ‘CASEFILE60’ for 60% off and FREE shipping <br>\n<a href=\"https://www.betterhelp.com/casefile\">BetterHelp</a> – Get 10% off your first month of professional counselling with a licensed therapist<br>\n<a href=\"https://www.zocdoc.com/casefile\">Zocdoc</a> –  Find a doctor near you<br>\n<br>\nFor all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-240-jasoninhell/\">casefilepodcast.com/case-240-jasoninhell</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8269985.mp3?modified=1685788468&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40384309.jpg"
                },
                {
                    "uuid": "5a73b156-f9d0-403c-8072-3f6087f13393",
                    "name": "Case 239: Peggy Carr",
                    "description": "<div>When 41-year-old waitress Peggy Carr succumbed to a mysterious illness in October 1988, doctors in Alturas, Florida struggled to figure out what was wrong with her. As other members of Peggy’s family became sick too, one neurologist came to suspect they were dealing with a case of poisoning. Tests soon confirmed the family had been deliberately poisoned with the rare heavy metal thallium, but no one could understand why. <br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Erin Munro<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>\n<br>\nFor all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-239-peggy-carr/\">casefilepodcast.com/case-239-peggy-carr</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8266159.mp3?modified=1685952010&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40362584.jpg"
                },
                {
                    "uuid": "bd345a17-ddbf-4d39-8051-9d5a9a69a42b",
                    "name": "Case 238: Renae Marsden",
                    "description": "<div>20-year-old Renae Marsden was a bright and bubbly young woman who valued her family above all else. Her mother Teresa Marsden was therefore shocked when she received a message from Renae’s boyfriend, Brayden Spiteri, on August 5 2013 warning: <em>“Sort your daughter out. Threatening to kill herself.”<br>\n<br>\n</em><a href=\"https://www.change.org/p/dominic-perrottet-driven-to-suicide-but-renae-s-abuser-in-the-clear-criminalising-catfishing\">Criminalising Catfishing Petition</a><br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Elsha McGill<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>For all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-238-renae-marsden/\">casefilepodcast.com/case-238-renae-marsden</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8257843.mp3?modified=1685952022&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40316469.jpg"
                },
                {
                    "uuid": "1b9d7b26-3a2c-4da4-8ecf-cd72507abea2",
                    "name": "Case 237: Rena & Danny Paquette",
                    "description": "<div>In February 1960, the city of Manchester, New Hampshire, was rocked by the violent murder of teenager Sandra Valade. Three years later, another teenager, Pamela Mason, was killed in the same manner. A quiet housewife named Rena Paquette confided to police that she knew who murdered the two teens. Just days after coming forward, she was found dead under mysterious circumstances by her son, Danny Paquette. <br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Jessica Forsayeth<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>For all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-237-rena-danny-paquette/\">casefilepodcast.com/case-237-rena-danny-paquette</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8257565.mp3?modified=1685952032&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40314927.jpg"
                },
                {
                    "uuid": "ff761b9f-f3f3-46ca-a707-3720ba03cff2",
                    "name": "Case 236: Sophie Lionnet",
                    "description": "<div>When residents of the affluent Southfields area of south-west London notice foul smelling smoke coming from a home on Wimbledon Park Drive in September 2017, firefighters arrive to make sure the house isn’t in danger. Nothing could prepare them for what they find instead – the burning human remains of French au pair, 21-year-old Sophie Lionnet. <br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Elsha McGill<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>This episode's sponsors:<br>\n<a href=\"https://tigertigertigerbook.com/\">Tiger, Tiger, Tiger</a> – Grab your copy of the book <br>\n<a href=\"https://www.rocketmoney.com/casefile\">Rocket Money</a> – Find and cancel subscriptions you no longer use<br>\n<a href=\"https://www.betterhelp.com/casefile\">BetterHelp</a> – Get 10% off your first month of professional counselling with a licensed therapist<br>\n<a href=\"https://wondery.com/shows/in-the-shadows/\">In the Shadows</a> – Listen to a new podcast from Casefile Presents (available exclusive on Wondery+) <br>\n<br>\nFor all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-236-sophie-lionnet/\">casefilepodcast.com/case-236-sophie-lionnet</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8253426.mp3?modified=1684670372&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40292308.jpg"
                },
                {
                    "uuid": "07b68342-34d6-4b63-bc91-b0b69dc58ebb",
                    "name": "Case 235: House of Horrors (Part 3)",
                    "description": "<div>[Part 3 of 3]<br>\nMore disturbing secrets are unearthed at 25 Cromwell Street as the investigation into Fred West leads detectives into the remote English countryside. Fred steadfastly asserts that his wife knew nothing of his crimes, and tight-lipped Rose maintains her innocence...<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Milly Raso<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a> and<a href=\"http://www.andrewjoslynmusic.com/\"> Andrew Joslyn</a><br>\n<br>\nThis episode's sponsors:<br>\n<a href=\"https://simplisafe.com/casefile\">SimpliSafe</a> – Get a free indoor security camera and 20% off your order <br>\n<a href=\"https://apps.apple.com/gb/app/doordash-food-delivery/id719972451\">DoorDash</a> – Get free delivery plus 50% off your first order of up to $20 value with promo code ‘CASEFILEPOD’ <br>\n<a href=\"https://www.smartnews.com/\">Smart News</a> – Download the app for free and get the news that matter most<br>\n<a href=\"https://wondery.com/shows/in-the-shadows/\">In the Shadows</a> – Listen to a new podcast from Casefile Presents (available exclusive on Wondery+)<br>\nFor all credits and sources please visit <a href=\"https://casefilepodcast.com/case-235-house-of-horrors-part-3/\">casefilepodcast.com/case-235-house-of-horrors-part-3</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8249253.mp3?modified=1684064132&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40268264.jpg"
                },
                {
                    "uuid": "b04cd1da-226e-4988-a497-bd64ee20bb48",
                    "name": "Case 235: House of Horrors (Part 2)",
                    "description": "<div>[Part 2 of 3]<br>\nBy 1992, Fred and Rose West were raising their children at their Cromwell Street home. At first glance, the Wests appeared to be a model family. Neighbours viewed Fred as a modest, kind and soft-spoken man. Rose was a dedicated mother and housewife... <br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Milly Raso<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a> and<a href=\"http://www.andrewjoslynmusic.com/\"> Andrew Joslyn</a><br>\n<br>\nThis episode's sponsors:<br>\n<a href=\"http://noom.com/casefile\">Noom Weight</a> – The last weight loss program you’ll need. Start your trial today<br>\n<a href=\"https://babbel.com/casefile\">Babbel</a> – Get up to 50% off your subscription<br>\n<a href=\"https://www.betterhelp.com/casefile\">BetterHelp</a> – Get 10% off your first month of professional counselling with a licensed therapist<br>\n<a href=\"https://www.article.com/casefile\">Article</a> – Get $50 off your first order of $100 or more<br>\nSubscribe for ad-free episodes and bonus content:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Join Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Join Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Join Patreon</a></li>\n</ul>\n<div>For all credits and sources please visit <a href=\"https://casefilepodcast.com/case-235-house-of-horrors-part-2/\">casefilepodcast.com/case-235-house-of-horrors-part-2</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8245820.mp3?modified=1684063704&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40249043.jpg"
                },
                {
                    "uuid": "07fc096e-2040-4231-9f6b-4c93fbf557d0",
                    "name": "Case 235: House of Horrors (Part 1)",
                    "description": "<div>[Part 1 of 3]<br>\nIn early 1969, 15-year-old Rose Letts was waiting alone at a bus stop in the English town of Cheltenham when she was approached by a much older man.  27-year-old Fred West was poorly dressed, dirty, and had a mouthful of green, chipped teeth from years of neglect. While Rose found Fred repulsive, something about him excited her. <br>\n<br>\nFrom this chance encounter, the pair initiated an intense relationship that culminated in their marriage three years later. Mr and Mrs West then settled into their ideal family home in the city of Gloucester - 25 Cromwell Street.<br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Milly Raso<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a> and<a href=\"http://www.andrewjoslynmusic.com/\"> Andrew Joslyn</a><br>\n<br>\nThis episode's sponsors:<br>\n<a href=\"http://shipstation.com/\">ShipStation</a> – Try ShipStation FREE for 60 days with promo code ‘CASEFILE’<br>\n<a href=\"https://www.betterhelp.com/casefile\">BetterHelp</a> – Get 10% off your first month of professional counselling with a licensed therapist<br>\n<a href=\"https://www.doordash.com/\">DoorDash</a> – Get 50% off up to $20 value and free delivery on your first order with promo code ‘CASEFILEPOD’<br>\n<a href=\"https://www.rocketmoney.com/casefile\">Rocket Money</a> – Find and cancel subscriptions you no longer use<br>\n<a href=\"https://www.hellofresh.com/casefile21\">Hello Fresh</a> – Use code ‘CASEFILE21’ for 21 free meals including FREE shipping *USA only*<br>\n<br>\nFor all credits and sources please visit <a href=\"https://casefilepodcast.com/case-235-house-of-horrors-part-1/\">casefilepodcast.com/case-235-house-of-horrors-part-1</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8241921.mp3?modified=1684063388&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40226182.jpg"
                },
                {
                    "uuid": "87d5206e-480f-4b85-a35e-8481ba045424",
                    "name": "Case 234: Franca Viola",
                    "description": "<div>In 1963, on the Italian island of Sicily, a wealthy young bachelor named Filippo Melodia began a courtship with a teenager named Franca Viola, much to the displeasure of Franca's father... <br>\n<br>\n---<br>\n<br>\nNarration – <a href=\"https://twitter.com/casefilehost\">Anonymous Host</a><br>\nResearch &amp; writing – Holly Boyd<br>\nCreative direction – Milly Raso<br>\nProduction and music – <a href=\"http://mikemigas.com/\">Mike Migas</a><br>\nMusic – <a href=\"http://www.andrewjoslynmusic.com/\">Andrew D.B. Joslyn</a><br>\n<br>\nSign up for Casefile Premium:</div>\n<ul>\n<li><a href=\"https://podcasts.apple.com/us/podcast/casefile-true-crime/id998568017?ign-itscg=30200S&amp;ign-itsct=casefile_podcasts\">Apple Premium</a></li>\n<li><a href=\"https://spotifyanchor-web.app.link/e/9gSwcv7USsb\">Spotify Premium</a></li>\n<li><a href=\"https://www.patreon.com/casefile\">Patreon</a></li>\n</ul>\n<div>This episode's sponsors:<br>\n<a href=\"https://simplisafe.com/casefile\">SimpliSafe</a> – Get 40% off any new security system<br>\n<a href=\"http://noom.com/casefile\">Noom Weight</a> – The last weight loss program you’ll need. Start your trial today<br>\n<a href=\"https://bestfiends.com/\">Best Fiends</a> – Download Best Fiends for free<br>\n<a href=\"http://shipstation.com/\">ShipStation</a> – Try ShipStation FREE for 60 days with promo code ‘CASEFILE’<br>\n<a href=\"https://pseudocidepodcast.com/\">Pseudocide</a> – New podcast from Casefile Presents about the disappearance of Patrick McDermott<br>\n<br>\nFor all credits and sources, please visit <a href=\"https://casefilepodcast.com/case-234-franca-viola/\">casefilepodcast.com/case-234-franca-viola</a>\n</div>\n",
                    "audioUrl": "https://pscrb.fm/rss/p/pdst.fm/e/audioboom.com/posts/8206974.mp3?modified=1678912872&sid=4940872&source=rss",
                    "imageUrl": "https://audioboom.com/i/40027908.jpg"
                }
            ],
            "totalEpisodesCount": 298,
            "genres": [
                "PODCASTSERIES_TRUE_CRIME",
                "PODCASTSERIES_HISTORY",
                "PODCASTSERIES_SOCIETY_AND_CULTURE"
            ],
            "itunesInfo": {
                "uuid": "5677f369-bb80-4862-af22-b75cd06bca71",
                "hash": "f969bb823ff12a5bbd1081f4f595abf773a1fd8ca75abed44bedf4670af9b4ec",
                "subtitle": null,
                "summary": "Fact is scarier than fiction. Subscribe to Casefile Premium to receive ad-free episodes released one week early, along with access to bonus Q&A’s, our exclusive show ‘Behind the Files’, and more.",
                "baseArtworkUrl": "https://is3-ssl.mzstatic.com/image/thumb/Podcasts115/v4/f0/d3/62/f0d36290-b222-397c-f1a5-02623a69b3f0/mza_9983181717749715502.jpg/",
                "baseArtworkUrlOf": "https://is3-ssl.mzstatic.com/image/thumb/Podcasts115/v4/f0/d3/62/f0d36290-b222-397c-f1a5-02623a69b3f0/mza_9983181717749715502.jpg/undefinedxundefinedbb.png",
                "publisherId": 1533870296,
                "publisherName": "Casefile Presents",
                "country": "UNITED_STATES_OF_AMERICA"
            },
            "seriesType": "EPISODIC",
            "language": "ENGLISH",
            "contentType": "AUDIO",
            "isExplicitContent": true,
            "copyright": "Casefile True Crime",
            "websiteUrl": "https://audioboom.com/channels/4940872-casefile-true-crime",
            "rssUrl": "https://audioboom.com/channels/4940872.rss",
            "rssOwnerName": null,
            "rssOwnerPublicEmail": "host@casefilepodcast.com",
            "authorName": "Casefile Presents"
        })
    }
}

export default dummyEpisodes;