
const topPodcasts = [
    { name: "The Joe Rogan Experience", authorName: "Joe Rogan" },
    { name: "Call Her Daddy", authorName: "Alex Cooper" },
    { name: "This Past Weekend", authorName: "Theo Von" },
    { name: "SmartLess", authorName: "Jason Bateman, Sean Hayes, Will Arnett" },
    { name: "Stay Free with Russell Brand", authorName: "Russell Brand" },
    { name: "Betrayal", authorName: "iHeartPodcasts and Glass Podcasts" },
    { name: "Huberman Lab", authorName: "Scicomm Media" },
    { name: "Crime Junkie", authorName: "audiochuck" },
    { name: "Shawn Ryan Show", authorName: "Shawn Ryan | Cumulus Podcast Network" },
    { name: "Distractible", authorName: "Distractible" },
    { name: "On Purpose with Jay Shetty", authorName: "iHeartPodcasts" },
    { name: "Scamanda", authorName: "Lionsgate Sound" },
    { name: "Lex Fridman Podcast", authorName: "Lex Fridman" },
    { name: "The Daily", authorName: "The New York Times" },
    { name: "The Horror of Dolores Roach", authorName: "Gimlet" },
    { name: "Aware & Aggravated", authorName: "Leo Skepi" },
    { name: "anything goes with emma chamberlain", authorName: "emma chamberlain" },
    { name: "2 Bears, 1 Cave with Tom Segura & Bert Kreischer", authorName: "YMH Studios" },
    { name: "Rotten Mango", authorName: "Stephanie Soo & Ramble" },
    { name: "Morbid", authorName: "Morbid Network | Wondery" },
    { name: "The Jordan B. Peterson Podcast", authorName: "Dr. Jordan B. Peterson" },
    { name: "The Squeeze", authorName: "Taylor Lautner " },
    { name: "Bad Friends", authorName: "Andrew Santino and Bobby Lee" },
    { name: "Matt and Shane's Secret Podcast", authorName: "D.A.W.G.Z." },
    { name: "Serial Killers", authorName: "Spotify Studios" },
    { name: "Who shat on the floor at my wedding?", authorName: "Who shat on the floor at my wedding?" },
    { name: "The Mel Robbins Podcast", authorName: "Mel Robbins" },
    { name: "You Should Know Podcast", authorName: "Wood Elf Media" },
    { name: "Armchair Expert with Dax Shepard", authorName: "Armchair Expert" },
    { name: "The Broski Report with Brittany Broski", authorName: "Brittany Broski & Audioboom Studios" },
    { name: "Cut the Camera with the Sturniolo Triplets", authorName: "Sturniolo Triplets" },
    { name: "Up First", authorName: "NPR" },
    { name: "Podcast P with Paul George", authorName: "Wave Sports + Entertainment" },
    { name: "The Basement Yard", authorName: "Santagato Studios" },
    { name: "Date Yourself Instead", authorName: "Lyss Boss" },
    { name: "I've Had It", authorName: "Jennifer Welch and Angie Sullivan " },
    { name: "Conan O’Brien Needs A Friend", authorName: "Team Coco & Earwolf" },
    { name: "Murder, Mystery & Makeup", authorName: "Audioboom Studios" },
    { name: "Dateline NBC", authorName: "NBC News" },
    { name: "Last Podcast On The Left", authorName: "The Last Podcast Network" },
    { name: "PBD Podcast", authorName: "PBD Podcast" },
    { name: "Stuff You Should Know", authorName: "iHeartPodcasts" },
    { name: "The Psychology of your 20s", authorName: "iHeartPodcasts" },
    { name: "The Journal.", authorName: "The Wall Street Journal" },
    { name: "Modern Wisdom", authorName: "Chris Williamson" },
    { name: "The Ben Shapiro Show", authorName: "The Daily Wire" },
    { name: "The Unplanned Podcast with Matt & Abby", authorName: "Matt & Abby" },
    { name: "Dumb Blonde", authorName: "Dumb Blonde Productions" },
    { name: "Conspiracy Theories", authorName: "Spotify Studios" },
    { name: "Your Mom's House with Christina P. and Tom Segura", authorName: "YMH Studios" },
    { name: "RFK Jr Podcast", authorName: "Robert Kennedy Jr" },
    { name: "This American Life", authorName: "This American Life" },
    { name: "Fly on the Wall with Dana Carvey and David Spade", authorName: "Cadence13" },
    { name: "The Sleep Zone Podcast", authorName: "Thesleepzonepodcast" },
    { name: "Rachel Maddow Presents: Déjà News", authorName: "Rachel Maddow, MSNBC" },
    { name: "Two Hot Takes", authorName: "Morgan Absher" },
    { name: "Motivation Daily by Motiversity", authorName: "Motiversity" },
    { name: "Search Engine", authorName: "PJ Vogt" },
    { name: "Scary Horror Stories by Dr. NoSleep", authorName: "Dr. NoSleep" },
    { name: "ShxtsNGigs", authorName: "shxtsngigs" },
    { name: "The Bald and the Beautiful with Trixie and Katya", authorName: "Studio71" },
    { name: "KILL TONY", authorName: "DEATHSQUAD.TV" },
    { name: "True Crime with Kendall Rae", authorName: "Mile Higher Media & Audioboom Studios" },
    { name: "The Mindset Mentor", authorName: "Rob Dial" },
    { name: "TED Talks Daily", authorName: "TED" },
    { name: "Morning Brew Daily", authorName: "Morning Brew" },
    { name: "Give It To Me Straight", authorName: "Give It To Me Straight" },
    { name: "Just Jack & Will with Sean Hayes and Eric McCormack", authorName: "SmartLess Media | Wondery" },
    { name: "The Tim Dillon Show", authorName: "The Tim Dillon Show" },
    { name: "NPR News Now", authorName: "NPR" },
    { name: "Normal Gossip", authorName: "Normal Gossip" },
    { name: "Hidden Brain", authorName: "Hidden Brain, Shankar Vedantam" },
    { name: "Wiser Than Me with Julia Louis-Dreyfus", authorName: "Lemonada Media" },
    { name: "Where Should We Begin? with Esther Perel", authorName: "Esther Perel Global Media" },
    { name: "El Podcast de Marian Rojas Estapé", authorName: "Marian Rojas Estapé" },
    { name: "The Diary Of A CEO with Steven Bartlett", authorName: "Steven Bartlett " },
    { name: "Dan Bongino Show", authorName: "Cumulus Podcast Network | Dan Bongino" },
    { name: "We Can Do Hard Things with Glennon Doyle", authorName: "Glennon Doyle & Cadence13" },
    { name: "Not An NBA Podcast with Kenny Beecham", authorName: "Kenny Beecham" },
    { name: "m4f audios mdom nsfw", authorName: "soph ??" },
    { name: "The Grand Intuitive666 ", authorName: "The Grand Intuitive 666" },
    { name: "Duncan Trussell Family Hour", authorName: "Duncan Trussell Family Hour" },
    { name: "The Always Sunny Podcast", authorName: "Megawatt Productions" },
    { name: "How to Talk to People", authorName: "The Atlantic" },
    { name: "Dungeons and Daddies", authorName: "Dungeons and Daddies" },
    { name: "Pardon My Take", authorName: "Barstool Sports" },
    { name: "Cancelled with Tana Mongeau", authorName: "Tana Mongeau & Studio71" },
    { name: "Andrew Schulz's Flagrant with Akaash Singh", authorName: "Andrew Schulz's Flagrant with Akaash Singh" },
    { name: "Suburb Talks", authorName: "Nick Grajeda" },
    { name: "Jocko Podcast", authorName: "Jocko DEFCOR Network" },
    { name: "The Witch Trials of J.K. Rowling", authorName: "The Free Press" },
    { name: "Tetragrammaton with Rick Rubin", authorName: "Rick Rubin" },
    { name: "The Ramsey Show", authorName: "Ramsey Network" },
    { name: "The Magnus Archives", authorName: "Rusty Quill" },
    { name: "Behind the Bastards", authorName: "iHeartPodcasts" },
    { name: "Ologies with Alie Ward", authorName: "Alie Ward" },
    { name: "The Peter Attia Drive", authorName: "Peter Attia, MD" },
    { name: "The Bill Simmons Podcast", authorName: "The Ringer" },
    { name: "Solved Murders: True Crime Mysteries", authorName: "Spotify Studios" },
    { name: "The King Road Killings: An Idaho Murder Mystery", authorName: "ABC News" }
]

export default topPodcasts;